# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outport < Formula
  desc "Dev port manager for multi-project, multi-worktree development"
  homepage "https://outport.app"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/outport/releases/download/v0.4.0/outport_0.4.0_darwin_amd64.tar.gz"
      sha256 "dab3a99e8683d25d3cabf64b6f4c1481bc4b07b5421f886943a3dc7cd3a307db"

      define_method(:install) do
        bin.install "outport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/outport/releases/download/v0.4.0/outport_0.4.0_darwin_arm64.tar.gz"
      sha256 "d92eb06d293d981a84e0fa012096dba08ac7d890083ca67ff0f120c4bf6a815d"

      define_method(:install) do
        bin.install "outport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/outport/releases/download/v0.4.0/outport_0.4.0_linux_amd64.tar.gz"
      sha256 "19d480676ddf84769f08f2213c9a3c9f6f646ecb552e476da93e7119d77ed250"
      define_method(:install) do
        bin.install "outport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/outport/releases/download/v0.4.0/outport_0.4.0_linux_arm64.tar.gz"
      sha256 "b2e2d752a96e52676cd4b663438cc636f5f0cedae57090c1fe25fb9464af2585"
      define_method(:install) do
        bin.install "outport"
      end
    end
  end
end
