# This file was generated by GoReleaser. DO NOT EDIT.
cask "outport" do
  name "outport"
  desc "Dev port manager for multi-project, multi-worktree development"
  homepage "https://outport.app"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "outport"

  on_macos do
    on_intel do
      url "https://github.com/steveclarke/outport/releases/download/v#{version}/outport_#{version}_darwin_amd64.tar.gz"
      sha256 "aae8945884152135731862fd6806d207ac7213b1063ecff7b455b7bfb96be485"
    end
    on_arm do
      url "https://github.com/steveclarke/outport/releases/download/v#{version}/outport_#{version}_darwin_arm64.tar.gz"
      sha256 "c15f1498f59893e1db019820c5fbca3539caa633afb53f660f22a12792b983b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/steveclarke/outport/releases/download/v#{version}/outport_#{version}_linux_amd64.tar.gz"
      sha256 "a47cbe17200c792badb801ac911f2f7b184a40de9e452bcb134d1767ec3d3943"
    end
    on_arm do
      url "https://github.com/steveclarke/outport/releases/download/v#{version}/outport_#{version}_linux_arm64.tar.gz"
      sha256 "93be62822564fc0f5141d2c79a375a09bffa2eeae2bd8e7d45b24ef259f2aca6"
    end
  end

  # No zap stanza required
end
