# typed: false
# frozen_string_literal: true

# This file is generated by the Clevertakes CLI release workflow. DO NOT EDIT.
class Ct < Formula
  desc "Agent-first CLI for Clevertakes"
  homepage "https://github.com/steveclarke/clevertakes"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.0/ct-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "76c4b1d9e3c2d5447de1f02fdb404f91d92232a8b83f3d57efd960c7a574aae9"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.0/ct-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "9e8658347357957a3cc866a37871e094b8dd578a6f3be4cd0badf7d41dda6119"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.0/ct-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "0d29dad2a2eea3ac6bcb1824e1af118e57d38e6b0aab49199143c86edc428f95"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.0/ct-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "03aec17c4b909efb6f31e2fd0da01dcf067c006315e32804675462d93be825f4"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ct version")
  end
end
