# typed: false
# frozen_string_literal: true

# This file is generated by the Clevertakes CLI release workflow. DO NOT EDIT.
class Ct < Formula
  desc "Agent-first CLI for Clevertakes"
  homepage "https://github.com/steveclarke/clevertakes"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.1/ct-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "ee76ffa6e7cd87581d1e37bbdf71b69ad6e3d7c68ab7eb3a8ba29b2e0b5cab0e"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.1/ct-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "91d935ac2740c1bf0fe0eb94dacc78b681bf98b453b2978e604c33cc1436bb1f"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.1/ct-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "79adc1fcef4cbbff97a46b025f13e27da071efca642b62feb5aca90cca6758f9"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ct-cli-v0.1.1/ct-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "ddfcb8b37bb17ec8cf69cd0ce6186da8953ecda38a97d5be06d217b333b0c996"

      define_method(:install) do
        bin.install "ct"
        bash_completion.install "completions/ct.bash" => "ct"
        zsh_completion.install "completions/_ct"
        fish_completion.install "completions/ct.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ct version")
  end
end
