# typed: false
# frozen_string_literal: true

# This file is generated by the Ninjanizr CLI release workflow. DO NOT EDIT.
class NinjanizrCli < Formula
  desc "Agent-first CLI for Ninjanizr inventory"
  homepage "https://app.ninjanizr.com"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.3.1/ninjanizr-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "63de6cee2956145be832031030009b54e42c13d5d3763f157b942b97465aa932"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.3.1/ninjanizr-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "efc96bcfb0a1391e303066dff890f20909ca453bffd78dc94d86ec5f4adac570"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.3.1/ninjanizr-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "1bf2bc2bd170309554eda235546bb84f1890a93f3e9dd2edeb717e564a161edb"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.3.1/ninjanizr-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "df50115b59875e1d8bc5115c1f4b1d556d74662c50ec1068c0cc6e7e9444c243"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nj version")
  end
end
