# typed: false
# frozen_string_literal: true

# This file is generated by the Ninjanizr CLI release workflow. DO NOT EDIT.
class NinjanizrCli < Formula
  desc "Agent-first CLI for Ninjanizr inventory"
  homepage "https://app.ninjanizr.com"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.2/ninjanizr-cli_0.5.2_darwin_amd64.tar.gz"
      sha256 "6e716084c957afb74e92d48fdd23e3afb80e321fccc5da7f4e90217113e2e59a"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.2/ninjanizr-cli_0.5.2_darwin_arm64.tar.gz"
      sha256 "5b07f620b63cc89e1490e0a714e68e6e2a9ffb9fd2857951b411b79e60e9a5ff"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.2/ninjanizr-cli_0.5.2_linux_amd64.tar.gz"
      sha256 "2ae8933c979fae59a4ebf27163f4b20aec70e6ee2f6bff9661db2dfa5a0d4a40"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.2/ninjanizr-cli_0.5.2_linux_arm64.tar.gz"
      sha256 "9a930897416cd241e20992297a280d4ff7f8318c6200e4ca47596da3e57d3bc2"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nj version")
  end
end
