# typed: false
# frozen_string_literal: true

# This file is generated by the Ninjanizr CLI release workflow. DO NOT EDIT.
class NinjanizrCli < Formula
  desc "Agent-first CLI for Ninjanizr inventory"
  homepage "https://app.ninjanizr.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.0/ninjanizr-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "602508bf7514413ef145810bd848942803cc08af2af7749c4b8b9a343c0ec15c"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.0/ninjanizr-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "3c7ac1c024d00748e8df7a9bba64f83e2014095cd1448cdaf32477bf9a81cb22"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.0/ninjanizr-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "adcb59e59dfea3ca0d107a3759a1c4ea211c606f9fdc56ae02d75d966aee8958"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/ninjanizr-cli-v0.5.0/ninjanizr-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "2b284caf8e50f0c1c3850662ce74e5d3144e3bd5237b4f761d56cdd7d0516936"

      define_method(:install) do
        bin.install "nj"
        bash_completion.install "completions/nj.bash" => "nj"
        zsh_completion.install "completions/_nj"
        fish_completion.install "completions/nj.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nj version")
  end
end
