# typed: false
# frozen_string_literal: true

# This file is generated by the 135 Main CLI local release command.
class Otf < Formula
  desc "CLI for 135 Main team content"
  homepage "https://onethreefive.app"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/otf-cli-v0.2.0/otf-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "60023356dfff521a008ca679c688a50e195d8435079d85ce19dd64a9b6bfb6ca"

      define_method(:install) do
        bin.install "otf"
        bash_completion.install "completions/otf.bash" => "otf"
        zsh_completion.install "completions/_otf"
        pkgshare.install "otf-agent.md"
        fish_completion.install "completions/otf.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/otf-cli-v0.2.0/otf-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "91ce2601ca6fc3f7c07766eecac745471da063f714c580e26e0defb955d1142a"

      define_method(:install) do
        bin.install "otf"
        bash_completion.install "completions/otf.bash" => "otf"
        zsh_completion.install "completions/_otf"
        pkgshare.install "otf-agent.md"
        fish_completion.install "completions/otf.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/otf-cli-v0.2.0/otf-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "dd2b7a5f9439de10bac1e28c0c268b55fd11570c78ec7534731c00cbeaab4de2"

      define_method(:install) do
        bin.install "otf"
        bash_completion.install "completions/otf.bash" => "otf"
        zsh_completion.install "completions/_otf"
        pkgshare.install "otf-agent.md"
        fish_completion.install "completions/otf.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/homebrew-tap/releases/download/otf-cli-v0.2.0/otf-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "90642f39b692ca3b45c78035d180e1484f3c7ddbff2eea35470f225df1441aa6"

      define_method(:install) do
        bin.install "otf"
        bash_completion.install "completions/otf.bash" => "otf"
        zsh_completion.install "completions/_otf"
        pkgshare.install "otf-agent.md"
        fish_completion.install "completions/otf.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/otf version")
  end
end
