# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ucmix < Formula
  desc "Control PreSonus StudioLive mixers over UCNET (unofficial)"
  homepage "https://github.com/steveclarke/ucmix"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.3.0/ucmix_0.3.0_darwin_amd64.tar.gz"
      sha256 "42552ac155525faac6490e0815b72cc85490c719b14d7668dd249808cee1a117"

      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.3.0/ucmix_0.3.0_darwin_arm64.tar.gz"
      sha256 "0aa19c0e65a0089ae05e4282fee8793efdaa3306eae0bf2966627d6fc2e7c96a"

      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.3.0/ucmix_0.3.0_linux_amd64.tar.gz"
      sha256 "e79621b188a6e45764416cc15b54ef44332323d1054da8d97c4c5044dd266d98"
      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.3.0/ucmix_0.3.0_linux_arm64.tar.gz"
      sha256 "9a5b7b187404b0cd59af1228851ada88fe06bf1df5d88e32dd9d09490a00a6af"
      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
  end

  test do
    system "#{bin}/ucmix --version"
  end
end
