# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ucmix < Formula
  desc "Control PreSonus StudioLive mixers over UCNET (unofficial)"
  homepage "https://github.com/steveclarke/ucmix"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.2.0/ucmix_0.2.0_darwin_amd64.tar.gz"
      sha256 "aaea9c2496c54442a21516619a82fcaba8c731bcaaa53775626536a93b96a811"

      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.2.0/ucmix_0.2.0_darwin_arm64.tar.gz"
      sha256 "0621640b5832b609f32c56bda5b99516f516b30698a621a236a101929586b662"

      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.2.0/ucmix_0.2.0_linux_amd64.tar.gz"
      sha256 "b0cf359aaebf7ab6158f5d161bb2fa8a403ecb067415358a4e8ded5f431e964e"
      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.2.0/ucmix_0.2.0_linux_arm64.tar.gz"
      sha256 "4c2a177cb691d8485a7c60a5ce8109466b0674dedc01635411fd7b2173bc3799"
      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
  end

  test do
    system "#{bin}/ucmix --version"
  end
end
