# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ucmix < Formula
  desc "Control PreSonus StudioLive mixers over UCNET (unofficial)"
  homepage "https://github.com/steveclarke/ucmix"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.5.0/ucmix_0.5.0_darwin_amd64.tar.gz"
      sha256 "cb633a3acd05f0f49a9f0a56b4ac007e3584b3aed26fb02f79697f181b7bf661"

      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.5.0/ucmix_0.5.0_darwin_arm64.tar.gz"
      sha256 "dfb3adf9194424aa4890835d6d71647c8fc716556e2d540af615a9d9a0caacda"

      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.5.0/ucmix_0.5.0_linux_amd64.tar.gz"
      sha256 "254208acf1e210d360b8fd9034b19e9a3222aaa09a6dcc6f73bdc0367e409c40"
      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveclarke/ucmix/releases/download/v0.5.0/ucmix_0.5.0_linux_arm64.tar.gz"
      sha256 "8b5afb606421c936087bbc0800df6a56b9f5a525b5340542b464bffc41f71d86"
      define_method(:install) do
        bin.install "ucmix"
        bash_completion.install "completions/ucmix.bash" => "ucmix"
        zsh_completion.install "completions/_ucmix"
        fish_completion.install "completions/ucmix.fish"
      end
    end
  end

  test do
    system "#{bin}/ucmix --version"
  end
end
